apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-app
    name: nginx
  name: nginx-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>2000年代初頭のホームページ</title>
      <style>
        body {
          background-color: #ffffcc;
          font-family: Arial, sans-serif;
          font-size: 14px;
          margin: 0;
          padding: 0;
        }
        h1 {
          color: #ff6600;
          font-size: 24px;
          margin: 20px 0 10px 0;
          text-align: center;
        }
        p {
          color: #000000;
          font-size: 16px;
          line-height: 1.5;
          margin: 10px 20px;
          text-align: justify;
        }
        a {
          color: #0000ff;
          text-decoration: none;
        }
        a:hover {
          text-decoration: underline;
        }
      </style>
    </head>
    <body>
      <h1>2000年代初頭のホームページ</h1>
      <p>ようこそ！このサイトは2000年代初頭のホームページを再現したものです。当時のWebサイトは、今と比べるとシンプルでしたが、それでも多くの人々にとって、インターネットという新しい世界を開く扉でした。</p>
      <p>当サイトでは、2000年代初頭に人気だったリンク集や掲示板、そして当時のトピックスを紹介しています。ぜひ、当時の雰囲気を味わってください。</p>
      <p>当サイトについてのご意見・ご感想は、<a href="mailto:webmaster@example.com">こちら</a>までお寄せください。</p>
    </body>
    </html>
