apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
    name: nginx
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx-app
    name: nginx
  type: LoadBalancer
  ports:
  - name: nginx-port
    port: 80
    protocol: TCP
    targetPort: nginx-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app
    name: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
      name: nginx
  template:
    metadata:
      labels:
        app: nginx-app
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-port
          protocol: TCP
        volumeMounts: # Pod上にマウントするファイルを定義
        - name: nginx-html-file # マウントしたいvolumeを指定
          mountPath: /usr/share/nginx/html/index.html # 配置するパスを指定(Nginxのデフォルトの公開ディレクトリは/usr/share/nginx/html)
          subPath: index.html # マウントするファイル名を指定
          readOnly: true
      volumes: # マウントしたいリソースを定義
        - name: nginx-html-file # Podにマウントするvolumeを定義
          configMap:
            name: nginx-html # 使用するConfigMapリソースを指定
            items: # ConfigMapリソースで定義した、どのファイルを使用するか指定する
            - key: "index.html"
              path: "index.html"
